export const GET_NOTES = "GET_NOTES";
export const SET_ACTIVE = "SET_ACTIVE";
export const HANDLE_NOTE_CHANGE = "HANDLE_NOTE_CHANGE";
export const SAVE_NOTE = "SAVE_NOTE";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const LOADER_STATUS_CHANGE = "LOADER_STATUS_CHANGE";
export const LOG_IN = "LOG_IN";
//export const DELETE_NOTE = "DELETE_NOTE";
// export const ADD_NOTE = "ADD_NOTE";